version: '3.8'

services:
  # Servicio de base de datos MySQL
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pruebainfodesign
      MYSQL_USER: pt-root
      MYSQL_PASSWORD: juan2002
    ports:
      - "3306:3306"
    volumes:
      - ./pruebatecnicainfodesignback:/docker-entrypoint-initdb.d


  # Servicio de la aplicación Node.js
  app:
    build: 
      context: ./pruebatecnicainfodesignback
      dockerfile: Dockerfile
    container_name: node-app
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  mysql-data: