version: '3.8'

services:
  # Servicio de base de datos MySQL
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pruebainfodesign
      MYSQL_USER: pt-root
      MYSQL_PASSWORD: juan2002
    ports:
      - "3306:3306"
    volumes:
      - ./pruebatecnicainfodesignback:/docker-entrypoint-initdb.d

  # Servicio de la aplicación Node.js
  app:
    build:
      context: ./pruebatecnicainfodesignback
      dockerfile: Dockerfile
    container_name: node-app
    restart: always
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pruebainfodesign
      MYSQL_USER: pt-root
      MYSQL_PASSWORD: juan2002
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build:
      context: ./front-infodesign
      dockerfile: Dockerfile
    container_name: vite-app
    restart: always
    environment:
      VITE_API_URL: http://localhost:4000/
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  mysql-data: